#!/bin/bash
# 2026-05-16 Phase 4b — More-assets test (24, 22, 21).
set -euo pipefail
cd "$(dirname "$0")/.."

SWEEP=./engine-rust/target/release/ftmo-sweep
OUT=scripts/cache_bakeoff/hunt_2026_05_16
mkdir -p "$OUT"
RESULTS="$OUT/phase4b_more.tsv"
: > "$RESULTS"
echo -e "label\tn\tP1\tP2\tcombined_pct" >> "$RESULTS"

VOTERS_V02="--signals regime --regime-min-votes 2 --regime-poc-z --regime-bb-z-mr --regime-use-supertrend --regime-use-hmm"
BTC_FILTER="--cross-asset-sym BTCUSDT --cross-asset-fast 9 --cross-asset-slow 21"
COMMON="--candles-dir scripts/cache_bakeoff --funding-dir scripts/cache_bakeoff --windows 334 --step-days 3 --threads 14"
BASE_CFG="2h-trend-v5-amber-max-passlock"

run() {
  local label="$1"; local n="$2"; local syms="$3"
  echo "[$label $n]"
  local p1=$($SWEEP $COMMON --symbols "$syms" --config "$BASE_CFG" --profit-target 0.10 $VOTERS_V02 $BTC_FILTER 2>&1 | tail -1 | grep -oE '[0-9]+\.[0-9]+%' | head -1 | tr -d '%')
  local p2=$($SWEEP $COMMON --symbols "$syms" --config "$BASE_CFG" --profit-target 0.05 $VOTERS_V02 $BTC_FILTER 2>&1 | tail -1 | grep -oE '[0-9]+\.[0-9]+%' | head -1 | tr -d '%')
  if [ -z "$p1" ] || [ -z "$p2" ]; then echo "[skip-empty] $label"; return; fi
  local c=$(awk -v a="$p1" -v b="$p2" 'BEGIN{printf "%.2f", a*b/100}')
  echo -e "$label\t$n\t$p1\t$p2\t$c" | tee -a "$RESULTS"
}

ALL24="AAVEUSDT,ADAUSDT,ALGOUSDT,ARBUSDT,ATOMUSDT,AVAXUSDT,BCHUSDT,BNBUSDT,BTCUSDT,DOGEUSDT,DOTUSDT,ETCUSDT,ETHUSDT,INJUSDT,LINKUSDT,LTCUSDT,NEARUSDT,RUNEUSDT,SANDUSDT,SOLUSDT,STXUSDT,TRXUSDT,UNIUSDT,XRPUSDT"

run "M00_19_baseline" 19 "AAVEUSDT,ADAUSDT,ALGOUSDT,ARBUSDT,ATOMUSDT,AVAXUSDT,BCHUSDT,BNBUSDT,BTCUSDT,DOTUSDT,ETCUSDT,ETHUSDT,LINKUSDT,LTCUSDT,NEARUSDT,SOLUSDT,TRXUSDT,UNIUSDT,XRPUSDT"
run "M01_24_full"     24 "$ALL24"
run "M02_20_plus_DOGE" 20 "AAVEUSDT,ADAUSDT,ALGOUSDT,ARBUSDT,ATOMUSDT,AVAXUSDT,BCHUSDT,BNBUSDT,BTCUSDT,DOGEUSDT,DOTUSDT,ETCUSDT,ETHUSDT,LINKUSDT,LTCUSDT,NEARUSDT,SOLUSDT,TRXUSDT,UNIUSDT,XRPUSDT"
run "M03_20_plus_INJ"  20 "AAVEUSDT,ADAUSDT,ALGOUSDT,ARBUSDT,ATOMUSDT,AVAXUSDT,BCHUSDT,BNBUSDT,BTCUSDT,DOTUSDT,ETCUSDT,ETHUSDT,INJUSDT,LINKUSDT,LTCUSDT,NEARUSDT,SOLUSDT,TRXUSDT,UNIUSDT,XRPUSDT"
run "M04_20_plus_RUNE" 20 "AAVEUSDT,ADAUSDT,ALGOUSDT,ARBUSDT,ATOMUSDT,AVAXUSDT,BCHUSDT,BNBUSDT,BTCUSDT,DOTUSDT,ETCUSDT,ETHUSDT,LINKUSDT,LTCUSDT,NEARUSDT,RUNEUSDT,SOLUSDT,TRXUSDT,UNIUSDT,XRPUSDT"
run "M05_20_plus_SAND" 20 "AAVEUSDT,ADAUSDT,ALGOUSDT,ARBUSDT,ATOMUSDT,AVAXUSDT,BCHUSDT,BNBUSDT,BTCUSDT,DOTUSDT,ETCUSDT,ETHUSDT,LINKUSDT,LTCUSDT,NEARUSDT,SANDUSDT,SOLUSDT,TRXUSDT,UNIUSDT,XRPUSDT"
run "M06_20_plus_STX"  20 "AAVEUSDT,ADAUSDT,ALGOUSDT,ARBUSDT,ATOMUSDT,AVAXUSDT,BCHUSDT,BNBUSDT,BTCUSDT,DOTUSDT,ETCUSDT,ETHUSDT,LINKUSDT,LTCUSDT,NEARUSDT,SOLUSDT,STXUSDT,TRXUSDT,UNIUSDT,XRPUSDT"
run "M07_22_no_DOGE_RUNE" 22 "AAVEUSDT,ADAUSDT,ALGOUSDT,ARBUSDT,ATOMUSDT,AVAXUSDT,BCHUSDT,BNBUSDT,BTCUSDT,DOTUSDT,ETCUSDT,ETHUSDT,INJUSDT,LINKUSDT,LTCUSDT,NEARUSDT,SANDUSDT,SOLUSDT,STXUSDT,TRXUSDT,UNIUSDT,XRPUSDT"

echo ""
echo "=== Phase 4b results ==="
sort -t$'\t' -k5 -rn "$RESULTS" | head -10
