#!/usr/bin/env python3
"""Commodity-carry executor for FTMO MT5 — the build that makes the modelled
pass-rate real.

The carry strategy needs three things done reliably, none of which survive
manual operation:
  1. INTRADAY EQUITY GUARD: close everything the moment today's equity is
     down -3.5% from the day's start (FTMO daily loss is -5%; the gap is the
     execution buffer). This single mechanism is worth ~+12pp funded
     probability in the MC — but only if it fires at 03:00 too.
  2. RE-OPEN next trading day after a stop (the MC assumes the book is back).
  3. BOOK SYNC: hold exactly what tools/commodity-carry-pilot/book.json says
     (generated by scripts/commodity_carry_pilot.py); rebalance when it
     changes, weekly in practice.

Day boundary = FTMO server midnight (CET/CEST, Europe/Prague) — the same
boundary the daily-loss rule uses.

Run (Windows, real MT5):   python tools/carry_executor.py --capital-check
Run (Linux, mock):         FTMO_MOCK=1 python tools/carry_executor.py --dry-run
One cycle (cron/testing):  python tools/carry_executor.py --once

State in tools/carry-executor-state/state.json (atomic writes). Telegram
notification on guard-stop and on errors if telegram_notify is configured.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import time
from datetime import datetime
from pathlib import Path
from zoneinfo import ZoneInfo

TOOLS = Path(__file__).resolve().parent
sys.path.insert(0, str(TOOLS))

if os.environ.get("FTMO_MOCK") == "1":
    import mock_mt5 as mt5  # type: ignore
else:  # pragma: no cover - real terminal only on Windows
    try:
        import MetaTrader5 as mt5  # type: ignore
    except ImportError:
        mt5 = None  # injected in tests via CarryExecutor(mt5mod=...)

SERVER_TZ = ZoneInfo("Europe/Prague")   # FTMO server day boundary (CET/CEST)
MAGIC = 77001                           # own range, no collision with ftmo_executor tf_offsets
LOT_TOL = 0.011                         # ignore diffs below broker lot step


def notify(msg: str) -> None:
    print(f"[carry] {msg}", flush=True)
    try:
        from telegram_notify import send_telegram  # type: ignore
        send_telegram(f"[carry-executor] {msg}")
    except Exception:
        pass


class CarryExecutor:
    def __init__(self, mt5mod, book_path: Path, state_dir: Path,
                 stop_frac: float = 0.035, dry_run: bool = False):
        self.mt5 = mt5mod
        self.book_path = Path(book_path)
        self.state_dir = Path(state_dir)
        self.state_dir.mkdir(parents=True, exist_ok=True)
        self.state_f = self.state_dir / "state.json"
        self.stop_frac = stop_frac
        self.dry_run = dry_run
        self.state = self._read_state()

    # ---------- state ----------
    def _read_state(self) -> dict:
        if self.state_f.exists():
            return json.loads(self.state_f.read_text())
        return {"day_key": None, "day_start_equity": None, "stopped_day": None}

    def _write_state(self) -> None:
        tmp = self.state_f.with_suffix(".tmp")
        tmp.write_text(json.dumps(self.state))
        os.replace(tmp, self.state_f)

    @staticmethod
    def _day_key(now: datetime | None = None) -> str:
        now = now or datetime.now(SERVER_TZ)
        return now.astimezone(SERVER_TZ).date().isoformat()

    # ---------- MT5 helpers ----------
    def _equity(self) -> float:
        acct = self.mt5.account_info()
        if acct is None:
            raise RuntimeError("account_info() returned None — terminal gone?")
        return float(acct.equity)

    def _positions(self) -> dict[str, float]:
        """{symbol: signed_lots} for our magic only."""
        out: dict[str, float] = {}
        for p in (self.mt5.positions_get() or []):
            if getattr(p, "magic", MAGIC) != MAGIC:
                continue
            sign = 1.0 if p.type == self.mt5.POSITION_TYPE_BUY else -1.0
            out[p.symbol] = out.get(p.symbol, 0.0) + sign * float(p.volume)
        return out

    def _send(self, symbol: str, lots: float, *, position_ticket=None) -> bool:
        """Market order; positive lots = buy, negative = sell."""
        if abs(lots) < LOT_TOL:
            return True
        side = self.mt5.ORDER_TYPE_BUY if lots > 0 else self.mt5.ORDER_TYPE_SELL
        req = {"action": self.mt5.TRADE_ACTION_DEAL, "symbol": symbol,
               "volume": round(abs(lots), 2), "type": side, "magic": MAGIC,
               "deviation": 50, "comment": "carry",
               "type_time": self.mt5.ORDER_TIME_GTC}
        if position_ticket is not None:
            req["position"] = position_ticket
        if self.dry_run:
            notify(f"DRY {('buy' if lots > 0 else 'sell')} {abs(lots):.2f} {symbol}")
            return True
        res = self.mt5.order_send(req)
        ok = res is not None and res.retcode == self.mt5.TRADE_RETCODE_DONE
        if not ok:
            notify(f"ORDER FAILED {symbol} {lots:+.2f}: "
                   f"{getattr(res, 'retcode', 'None')}")
        return ok

    # ---------- core actions ----------
    def close_all(self) -> None:
        for p in (self.mt5.positions_get() or []):
            if getattr(p, "magic", MAGIC) != MAGIC:
                continue
            sign = -1.0 if p.type == self.mt5.POSITION_TYPE_BUY else 1.0
            self._send(p.symbol, sign * float(p.volume),
                       position_ticket=getattr(p, "ticket", None))

    def load_book(self) -> dict[str, float]:
        """{symbol: signed_lots} from the pilot's book.json."""
        book = json.loads(self.book_path.read_text())
        out = {}
        for sym, pos in book["positions"].items():
            out[sym] = pos["lots"] if pos["side"] == "long" else -pos["lots"]
        return out

    def sync_book(self) -> None:
        target = self.load_book()
        held = self._positions()
        for sym in sorted(set(target) | set(held)):
            delta = target.get(sym, 0.0) - held.get(sym, 0.0)
            if abs(delta) >= LOT_TOL:
                self._send(sym, delta)

    # ---------- one poll cycle ----------
    def poll_once(self, now: datetime | None = None) -> str:
        today = self._day_key(now)
        eq = self._equity()

        if self.state["day_key"] != today:               # server-day rollover
            self.state["day_key"] = today
            self.state["day_start_equity"] = eq
            self._write_state()

        day_start = self.state["day_start_equity"] or eq
        stopped_today = self.state.get("stopped_day") == today

        if not stopped_today and eq <= day_start * (1.0 - self.stop_frac):
            self.close_all()
            self.state["stopped_day"] = today
            self._write_state()
            notify(f"DAILY STOP: equity {eq:.2f} <= "
                   f"{day_start * (1 - self.stop_frac):.2f} "
                   f"(-{100 * self.stop_frac:.1f}% of day start) — book closed "
                   f"until next server day")
            return "stopped"

        if stopped_today:
            return "halted"                               # flat until rollover

        self.sync_book()
        return "synced"


def main() -> None:  # pragma: no cover - thin CLI wrapper
    ap = argparse.ArgumentParser()
    ap.add_argument("--book", default=str(TOOLS / "commodity-carry-pilot" / "book.json"))
    ap.add_argument("--state-dir", default=str(TOOLS / "carry-executor-state"))
    ap.add_argument("--stop", type=float, default=0.035)
    ap.add_argument("--poll", type=float, default=30.0, help="seconds")
    ap.add_argument("--once", action="store_true")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    if mt5 is None:
        sys.exit("MetaTrader5 not available — run on Windows or with FTMO_MOCK=1")
    if not mt5.initialize():
        sys.exit(f"mt5.initialize() failed: {mt5.last_error()}")
    notify(f"started — stop {100*args.stop:.1f}%, book {args.book}, "
           f"{'DRY-RUN' if args.dry_run else 'LIVE'}")
    ex = CarryExecutor(mt5, Path(args.book), Path(args.state_dir),
                       stop_frac=args.stop, dry_run=args.dry_run)
    while True:
        try:
            ex.poll_once()
        except Exception as e:
            notify(f"poll error: {e}")
        if args.once:
            break
        time.sleep(args.poll)


if __name__ == "__main__":
    main()
